# -*- coding: utf-8 -*-
"""Expensetracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mEiPteEE4GDlqrz8vBGqCTkJZWM7Tfu
"""

import csv
from datetime import datetime
import matplotlib.pyplot as plt

# File to store expenses
FILE_NAME = "expenses.csv"

def add_expense():
    name = input("Enter expense name: ")
    category = input("Enter category (Food/Travel/Shopping/Other): ")
    amount = float(input("Enter amount: "))
    date = input("Enter date (YYYY-MM-DD) or press Enter for today: ")

    if date.strip() == "":
        date = datetime.today().strftime('%Y-%m-%d')

    # Save to CSV
    with open(FILE_NAME, mode="a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([name, category, amount, date])

    print("✅ Expense added successfully!")

def view_expenses():
    try:
        with open(FILE_NAME, mode="r") as file:
            reader = csv.reader(file)
            print("\n--- All Expenses ---")
            for row in reader:
                print(f"Name: {row[0]}, Category: {row[1]}, Amount: ₹{row[2]}, Date: {row[3]}")
    except FileNotFoundError:
        print("⚠️ No expenses found. Add some first!")

def plot_expenses():
    # Read expenses
    expenses = {}
    try:
        with open(FILE_NAME, mode="r") as file:
            reader = csv.reader(file)
            for row in reader:
                category = row[1]
                amount = float(row[2])
                if category in expenses:
                    expenses[category] += amount
                else:
                    expenses[category] = amount
    except FileNotFoundError:
        print("⚠️ No expenses found. Add some first!")
        return

    # Plot pie chart
    categories = list(expenses.keys())
    amounts = list(expenses.values())

    plt.figure(figsize=(6,6))
    plt.pie(amounts, labels=categories, autopct='%1.1f%%', startangle=90)
    plt.title("Expenses by Category")
    plt.show()

def main_menu():
    while True:
        print("\n===== Personal Expense Tracker =====")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Plot Expenses")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            add_expense()
        elif choice == '2':
            view_expenses()
        elif choice == '3':
            plot_expenses()
        elif choice == '4':
            print("👋 Exiting. Goodbye!")
            break
        else:
            print("⚠️ Invalid choice. Please enter 1-4.")

main_menu()

main_menu()



